### ISSUE TITLE
Unclear if the 2.3.5 fix is working right for this?

### ISSUE THREAD

**Issue by MyklClason** [cloudconvert/cloudconvert-cli#15]
I have it set to use the 2.0.3 version in my package.json file and have pushed that to heroku, but it doesn't fix the issue for heroku or locally.

https://github.com/cloudconvert/cloudconvert-node/issues/109

The above suggests there may be additional change(s) required than just upgrading the required version.

I'm in contact with support as well on this as well, but unclear how to resolve. My only usage for this is to take an input excel file and convert it into a CSV for more efficient processing (Ruby is a RAM hog for large excel files).

**Comment by josiasmontag** [comment]
Version `2.0.3` of the CLI enforces version `2.3.5` of the SDK. If you updated correctly, you are all set.

**Comment by MyklClason** [comment]
Unsure. It seems to have resolved itself for now and is back to working again.
