### ISSUE TITLE
Error connecting key

### ISSUE THREAD

**Issue by C0NNECT0R** [cloudconvert/cloudconvert-cli#5]
```
C:\Windows\system32>export CLOUDCONVERT_API_KEY=iHfh6UVVWkbpV8z1f1pycY2yiyKsfb9ZBUVQ9d5vUP0cM67qmBA6DtVpXIglhXQe

"export" is not an internal or external command, executable program or batch file.
```

Help please i cant connect the key in command line

**Comment by josiasmontag** [comment]
`export` is not available on Windows, use `set` instead. 
And you should change your API key.

**Comment by C0NNECT0R** [comment]
in short as I understood, for windows it is useless, I tried all the commands that the command line itself offered me, and nothing.
